CREATE DATABASE IF NOT EXISTS pacman_db;
USE pacman_db;


CREATE TABLE IF NOT EXISTS scores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pseudo VARCHAR(50) NOT NULL,
    score INT NOT NULL,
    date_atteinte DATETIME DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO scores (pseudo, score) VALUES ('Test', 5000);